version: '3'

networks:
  backend:

services:
  backend:
    build:
      context: ./docker/backend
    volumes:
      - ./backend:/var/www
    depends_on:
      - db
    networks:
      - backend
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "8888:80"
    depends_on:
      - backend
    networks:
      - backend
  db:
    build:
      context: ./docker/db
    environment:
      - MYSQL_DATABASE=todoist
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypass
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "8889:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - backend