<?php

/**
 * Task
 *
 * PHP version 7.1
 *
 * @package todoist\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace todoist\Model;

use todoist\Interfaces\ModelInterface;

/**
 * Task
 *
 * @package todoist\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class Task implements ModelInterface
{
    private const MODEL_SCHEMA = <<<'SCHEMA'
{
  "type" : "object",
  "properties" : {
    "id" : {
      "type" : "integer"
    },
    "description" : {
      "type" : "string"
    },
    "completed_at" : {
      "type" : "integer"
    },
    "created_at" : {
      "type" : "integer"
    }
  }
}
SCHEMA;

    /** @var int $id */
    private $id;

    /** @var string $description */
    private $description;

    /** @var int $completedAt */
    private $completedAt;

    /** @var int $createdAt */
    private $createdAt;

    /**
     * Returns model schema.
     *
     * @param bool $assoc When TRUE, returned objects will be converted into associative arrays. Default FALSE.
     *
     * @return array
     */
    public static function getOpenApiSchema($assoc = false)
    {
        return json_decode(static::MODEL_SCHEMA, $assoc);
    }
}
