<?php
namespace todoist\Api;

use Psr\Container\ContainerInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Message\ResponseInterface;
use Exception;

// TODO: find a way to use Model generated by the openapi

/**
 * Cool, this is my own task implementation and
 *   all the other heavy lifting is done from the openapi-generator
 */
class TaskApi extends AbstractTaskApi
{
    public function completeTask(ServerRequestInterface $request, ResponseInterface $response, array $args)
    {
        $id = $args['id'];

        $response->getBody()->write($message);
        return $response->withStatus(501);
    }

    public function createTask(ServerRequestInterface $request, ResponseInterface $response, array $args)
    {
        $body = $request->getParsedBody();

        $response->getBody()->write($message);
        return $response->withStatus(501);
    }

    public function deleteTask(ServerRequestInterface $request, ResponseInterface $response, array $args)
    {
        $headers = $request->getHeaders();
        $apiKey = $request->hasHeader('api_key') ? $headers['api_key'] : null;
        $id = $args['id'];
        

        $response->getBody()->write($message);
        return $response->withStatus(501);
    }

    public function tasksGet(ServerRequestInterface $request, ResponseInterface $response, array $args)
    {
        $data = array('id' => 1);
        $response->getBody()->write(json_encode($data));
        return $response;
    }

    public function updateTask(ServerRequestInterface $request, ResponseInterface $response, array $args)
    {
        $headers = $request->getHeaders();
        $apiKey = $request->hasHeader('api_key') ? $headers['api_key'] : null;
        $id = $args['id'];
        $body = $request->getParsedBody();

        $response->getBody()->write($message);
        return $response->withStatus(501);
    }
}