<?php
namespace todoist\Api;

use Psr\Container\ContainerInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Message\ResponseInterface;
use Exception;
use todoist\Services\Db;

// TODO: find a way to use Model generated by the openapi
// TODO: Find a way to use the DI container here...

/**
 * Cool, this is my own task implementation and
 *   all the other heavy lifting is done from the openapi-generator
 */
class TaskApi extends AbstractTaskApi
{
    /**
     * @var Db
     */
    protected $db;
    public function __construct(ContainerInterface $container = null, Db $db)
    {
        parent::__construct($container);
        $this->db = $db;
    }

    public function completeTask(ServerRequestInterface $request, ResponseInterface $response, array $args)
    {
        $id = $args['id'];

        $response->getBody()->write($message);
        return $response->withStatus(501);
    }

    public function createTask(ServerRequestInterface $request, ResponseInterface $response, array $args)
    {
        $body = $request->getParsedBody();

        $response->getBody()->write($message);
        return $response->withStatus(501);
    }

    public function deleteTask(ServerRequestInterface $request, ResponseInterface $response, array $args)
    {
        $headers = $request->getHeaders();
        $apiKey = $request->hasHeader('api_key') ? $headers['api_key'] : null;
        $id = $args['id'];
        

        $response->getBody()->write($message);
        return $response->withStatus(501);
    }

    public function getTasks(ServerRequestInterface $request, ResponseInterface $response, array $args)
    {
        $data = $this->db->conn()->query("SELECT * FROM tasks")->fetchAll();
        $response->getBody()->write(json_encode($data));
        return $response;
    }

    public function updateTask(ServerRequestInterface $request, ResponseInterface $response, array $args)
    {
        $headers = $request->getHeaders();
        $apiKey = $request->hasHeader('api_key') ? $headers['api_key'] : null;
        $id = $args['id'];
        $body = $request->getParsedBody();

        $response->getBody()->write($message);
        return $response->withStatus(501);
    }
}